version: "3.9"

services:
  db:
    image: mysql
    restart: ${RESTART}
    environment:
# Omit hashtags for the 1st run, connect to the database to change the root password

#      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
#      MYSQL_ONETIME_PASSWORD: True
      MYSQL_USER_FILE: /run/secrets/mysql_user_name
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - ${VOLUME_PATH}/Wordpress/MySQL/:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - proxied
    secrets:
      - mysql_root_password
      - mysql_user_name
      - mysql_user_password


  wordpress:
    depends_on:
      - db
    image: wordpress:php8.3-apache
    restart: ${RESTART}
    ports:
      - "18000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER_FILE: /run/secrets/mysql_user_name
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_user_password
      WORDPRESS_DB_NAME: ${DATABASE}
    volumes:
      - ${VOLUME_PATH}/Wordpress:/var/www/html
    networks:
      - proxied
    secrets:
      - mysql_user_name
      - mysql_user_password
networks:
  proxied:
    external: true
    name: proxied

secrets:
  mysql_root_password:
    file: dockerSecrets/MySQLroot.txt
  mysql_user_name:
    file: dockerSecrets/MySQLuser.txt
  mysql_user_password:
    file: dockerSecrets/MySQLuserpw.txt
